# Generated by Django 5.0.3 on 2024-03-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-date_publisher'], 'verbose_name': 'История', 'verbose_name_plural': 'Истории'},
        ),
        migrations.AddField(
            model_name='story',
            name='poster',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='story',
            name='summary',
            field=models.CharField(blank=True, max_length=250, verbose_name='Краткое описание'),
        ),
    ]
