# Generated by Django 5.0.3 on 2024-03-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_catalog', '0002_alter_story_options_story_poster_alter_story_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Постер'),
        ),
    ]
