# Generated by Django 5.0.3 on 2024-03-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_catalog', '0004_alter_story_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='story',
            managers=[
            ],
        ),
    ]
