# Generated by Django 5.0.3 on 2024-03-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_catalog', '0005_alter_story_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Постер'),
        ),
    ]
